CREATE ROLE postgres LOGIN
  SUPERUSER INHERIT CREATEDB CREATEROLE REPLICATION;
CREATE DATABASE voip
  WITH OWNER = postgres
    ENCODING = 'UTF8'
    TABLESPACE = pg_default
    LC_COLLATE = 'Russian_Russia.1251'
    LC_CTYPE = 'Russian_Russia.1251'
    CONNECTION LIMIT = -1;

/*
CREATE USER postgres;
CREATE DATABASE voip;
GRANT ALL PRIVILEGES ON DATABASE docker TO docker;
*/